POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email": "teste2@labenu.com.br",
    "password": "654321",
    "role": "NORMAL"
}

###
# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

# {
#     "email": "teste2@labenu.com.br",
#     "password": "654321"
# }
{
    "email": "teste@labenu.com.br",
    "password": "123456"
}

###
@token = {{login.response.body.token}}
GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: {{token}}

###
@token = {{login.response.body.token}}
DELETE http://localhost:3003/user/ba9fcbba-0e59-43aa-93c8-38e4d0005055
Content-Type: application/json
Authorization: {{token}}